variable "external_allow_access_id" {}
variable "allow_web_id" {}
variable "availability_zones" {}
variable "amis" {}
variable "region" {}
variable "public_1_id" {}
variable "public_2_id" {}
variable "instance_type" {}
variable "private_key_path" {}
variable "key_name" {}
variable "ec2_name" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_desired" {}
variable "lb_type" {}
variable "lb_term" {}
variable "p_lc" {}
variable "f_delete" {}
variable "proto" {}
variable "port" {}
variable "customer_vpc_id" {}
variable "lb_tg_name" {}
variable "customer_efs" {}
variable "efs_performance" {}
variable "customer_name" {}
variable "counter" {}
