variable "vpc_cidr" {}
variable "prod_public_snet_1_cidr" {}
variable "prod_public_snet_2_cidr" {}
variable "region" {}
variable "customer_vpc_prod_id" {}
variable "local-ips" {}
variable "prod_private_snet_1_cidr" {}
variable "prod_private_snet_2_cidr" {}
variable "prod_rds_sg" {}
variable "prod_rds_sg_local" {}
variable "prod_allow_web_id" {}
variable "prod_mem_sg_local" {}
variable "prod_mem_sg" {}