variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_type" {}
variable "prod_rds_name" {}
variable "dbusername" {}
variable "dbpassword" {}
variable "rds_backup_period" {}
variable "prod_rds_sg_id" {}
variable "prod_rds_id" {}
variable "prod_rds_sg_local_id" {}
variable "prod_customer_name" {}
variable "skip_f_snap" {}
variable "multi_az" {}
variable "storage" {}
variable "rds_replica_type" {}
variable "mem_engine" {}
variable "mem_type" {}
variable "mem_port" {}
variable "cache_nodes" {}
variable "mem_az" {}
variable "prod_mem_sg_id" {}
variable "prod_mem_sg_local_id" {}
variable "customer_vpc_prod_id" {}
variable "prod_customer_private_1_id" {}
variable "prod_customer_private_2_id" {}
variable "region" {}
