version: '2'

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - lempnet
    depends_on: 
      - php
    hostname: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
    volumes_from:
      - php

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - lempnet
    hostname: php
    env_file:
      - ./php/php.env
    restart: always
    volumes:
      - "./docroot:/var/www/html"
    working_dir: /var/www/html

  mysql:
    build:
      context: ./db/
      dockerfile: Dockerfile
    env_file:
      - ./db/db.env
    networks:
      - lempnet
    hostname: mysql
    restart: always
    volumes:
      - "./db/db_data:/var/lib/mysql"

networks:
  lempnet:
     driver: bridge
