variable "prod_external_allow_access_id" {}
variable "prod_allow_web_id" {}
variable "prod_lb_web_id" {}
variable "availability_zones" {}
variable "amis" {}
variable "bastion_ami" {}
variable "region" {}
variable "prod_customer_private_1_id" {}
variable "prod_customer_private_2_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "ec2_name" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_desired" {}
variable "lb_type" {}
variable "lb_term" {}
variable "p_lc" {}
variable "f_delete" {}
variable "proto" {}
variable "port" {}
variable "customer_vpc_prod_id" {}
variable "lb_tg_name" {}
variable "customer_efs" {}
variable "efs_performance" {}
variable "prod_customer_name" {}
variable "counter" {}
variable "prod_public_1_id" {}
variable "prod_public_2_id" {}
variable "prod_memcache_cluster_ep" {}
variable "prod_rds_instance_ep" {}
variable "dbpassword" {}
variable "dbusername" {}
variable "False" {}
variable "True" {}
variable "ng-port" {}
variable "wp-port" {}
variable "customer" {}
variable "instance_type_bastion" {}
variable "prod_bastion_ssh_id" {}
variable "vol_size" {}
variable "admin" {}
variable "description" {}
variable "wp-content" {}
variable "email" {}
variable "url" {}
variable "template" {}
variable "title" {}
variable "theme_ss" {}
variable "c_status" {}
variable "wp_max_mem" {}
variable "wp_mem" {}
variable "delay" {}
